[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

tokio = { version = "1.18", features = ["full"] }
tungstenite = "0.17"
tokio-tungstenite = "0.17"
futures = "0.3"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
ndarray =  { version = "0.15", features = ["serde"] }
twmap = "0.7"
pretty_env_logger = "0.4"
log = "0.4"
glob = "0.3"
parking_lot = "0.12"